# Generated by Django 6.0.5 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_adaptive_exam_refactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexamattempt",
            name="attempt_type",
            field=models.CharField(
                choices=[
                    ("DIAGNOSTIC", "Diagnóstico"),
                    ("REINFORCEMENT", "Reforzamiento"),
                ],
                default="DIAGNOSTIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userexamattempt",
            name="title",
            field=models.CharField(default="Examen diagnóstico", max_length=255),
        ),
    ]
