# Generated by Django 5.2.14 on 2026-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_userexamattempt_attempt_type_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='competency_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_level',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
