# Generated by Django 6.0.5 on 2026-05-16 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Estudiante'), ('TEACHER', 'Profesor')], db_index=True, default='STUDENT', max_length=20, verbose_name='rol'),
        ),
        migrations.CreateModel(
            name='StudentLoginActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='logueado en')),
                ('date', models.DateField(db_index=True, verbose_name='fecha')),
                ('source', models.CharField(choices=[('MOBILE_APP', 'Mobile App')], default='MOBILE_APP', max_length=30, verbose_name='origen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'actividad de login estudiante',
                'verbose_name_plural': 'actividades de login estudiante',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['date', 'source'], name='account_stu_date_dec59d_idx'), models.Index(fields=['user', 'logged_at'], name='account_stu_user_id_1a4402_idx')],
            },
        ),
    ]
